{ config, inputs, ... }:
let
  mailboxMappings = import ./mailbox-mappings.nix;
  mailboxList = builtins.map (m: m.mailbox) mailboxMappings;
  autoScript = builtins.concatStringsSep "\n" (builtins.map
    (m: ''
      if address :is ["to, "cc"] "${m.address}" {
        fileinto "${m.mailbox}";
        stop;
      }'')
    mailboxMappings);
in
{
  imports = [
    (builtins.fetchTarball {
      # master as of 2026-04-08
      url = "https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/archive/c45a1e4385e81b937b353ee4ce97f5cfd60ceff2/nixos-mailserver-c45a1e4385e81b937b353ee4ce97f5cfd60ceff2.tar.gz";
      sha256 = "1ichglc8dc2an11avxk3lc6fqf455xsbbflva1dj8n7jcb72h82d";
    })
  ];

  networking.domain = "dev";

  networking.firewall.interfaces.ens5 = {
    allowedTCPPorts = [
      80 # HTTP
      443 # HTTPS

      53 # DNS
      22 # SSH
      822 # railreader
    ];
    allowedUDPPorts = [
      # QUIC
      80 # HTTP
      443 # HTTPS

      53 # DNS
    ];
  };

  services.fail2ban = {
    enable = true;
    bantime = "8h";
    bantime-increment = {
      enable = true;
      rndtime = "30m";
      maxtime = "168h";
    };
    jails = {
      sshd.settings = {
        enabled = true;
        mode = "aggressive";
      };
      dovecot.settings = {
        enabled = true;
        mode = "aggressive";
      };
      postfix.settings = {
        enabled = true;
        mode = "aggressive";
      };
    };
  };

  age.secrets.mail-hashed-password.file = ../../secrets/mail-hashed-password.age;
  age.secrets.radicale-htpasswd = {
    file = ../../secrets/radicale-htpasswd.age;
    owner = "radicale";
    group = "radicale";
    mode = "400";
  };

  # Manually set DNS nameservers, to avoid trying to use our own non-recursive BIND service.
  environment.etc."resolv.conf".text = ''
    # Generated by NixOS
    nameserver 1.1.1.1
    nameserver 1.0.0.1
  '';

  mailserver = {
    enable = true;
    stateVersion = 3;
    localDnsResolver = false;

    fqdn = "mail.edwardh.dev";
    sendingFqdn = "edwardh.dev";
    domains = [ "edwardh.dev" ];

    accounts = {
      "inbox@edwardh.dev" = {
        # mkpasswd -sm bcrypt
        hashedPasswordFile = config.age.secrets.mail-hashed-password.path;
        aliases = [ "@edwardh.dev" ];
        sieveScript =
          builtins.concatStringsSep "\n" [ (builtins.readFile ./mail.sieve) autoScript ];
      };
    };

    mailboxes = {
      # Special mailboxes
      Drafts = {
        auto = "subscribe";
        specialUse = "Drafts";
      };
      Junk = {
        auto = "subscribe";
        specialUse = "Junk";
      };
      Sent = {
        auto = "subscribe";
        specialUse = "Sent";
      };
      Trash = {
        auto = "subscribe";
        specialUse = "Trash";
      };
      Archives = {
        auto = "subscribe";
        specialUse = "Archive";
      };

      # non-auto-sorted mailboxes
      "Shipping and Recipts" = { auto = "subscribe"; };
      "School" = { auto = "subscribe"; };
      "Performances" = { auto = "subscribe"; };
      "Music" = { auto = "subscribe"; };
    } // builtins.listToAttrs
      (builtins.map
        (m: { name = m; value = { auto = "subscribe"; }; })
        mailboxList);

    x509.useACMEHost = "mail.edwardh.dev";
  };

  services.roundcube = {
    enable = true;
    # Web interface accessible from hostName.
    hostName = "mail.edwardh.dev";
    extraConfig = ''
      $config['smtp_server'] = "tls://${config.mailserver.fqdn}";
      $config['smtp_user'] = "%u";
      $config['smtp_pass'] = "%p";
    '';
  };

  services.radicale = {
    enable = true;
    settings = {
      server.hosts = [ "127.0.0.1:5232" ];
      auth = {
        type = "htpasswd";
        htpasswd_filename = config.age.secrets.radicale-htpasswd.path;
        htpasswd_encryption = "bcrypt";
      };
    };
  };

  services.bind = {
    enable = true;
    ipv4Only = true;
    extraOptions = ''
      recursion no;
      allow-transfer { none; };
      version "not currently available";
    '';
    zones."edwardh.dev" = {
      master = true;
      file = ./db.edwardh.dev;
      allowQuery = [ "any" ];
    };
  };

  security.acme.acceptTerms = true;
  security.acme.defaults.email = "security@edwardh.dev";

  services.nginx = {
    enable = true;
    appendHttpConfig = ''
      map $sent_http_content_type $expires {
        default                    off;
        text/html                  epoch;
        text/css                   1h;
      }
    '';
    appendConfig = ''
      stream {
        upstream railreader {
          server 172.27.3.51:64022;
        }
        server {
          listen 822;
          proxy_pass railreader;
        }
      }
    '';
    virtualHosts = {
      "edwardh.dev" = {
        default = true;

        addSSL = true;
        enableACME = true;
        quic = true;
        http3 = true;
        http3_hq = true;

        locations."/" = {
          root = inputs.edwardh-dev.packages.edwardh-dev;
          extraConfig = ''
            gzip on;
            gzip_types text/html text/css;
            etag on;
            expires $expires;
            add_header Alt-Svc 'h3=":443"; ma=86400';
          '';
        };
      };
      "calendar.edwardh.dev" = {
        forceSSL = true;
        enableACME = true;
        quic = true;
        http3 = true;
        http3_hq = true;

        locations."/" = {
          recommendedProxySettings = true;
          proxyPass = "http://127.0.0.1:5232";
          extraConfig = ''
            add_header Alt-Svc 'h3=":443"; ma=86400';
          '';
        };
        serverAliases = [ "contacts.edwardh.dev" ];
      };
      # Local services
      "cache.edwardh.dev" = {
        forceSSL = true;
        enableACME = true;
        quic = true;
        http3 = true;
        http3_hq = true;

        locations."/" = {
          recommendedProxySettings = true;
          proxyPass = "http://172.27.3.51:8501"; # rpi5-01
          extraConfig = ''
            add_header Alt-Svc 'h3=":443"; ma=86400';
            proxy_read_timeout 300;
          '';
        };
      };
      "lcd.edwardh.dev" = {
        addSSL = true;
        enableACME = true;
        locations."/" = {
          recommendedProxySettings = true;
          proxyPass = "http://172.27.3.42:8019"; # rpi4-02
        };
      };
      "grafana.edwardh.dev" = {
        forceSSL = true;
        enableACME = true;
        quic = true;
        http3 = true;
        http3_hq = true;

        locations."/" = {
          recommendedProxySettings = true;
          proxyWebsockets = true;
          proxyPass = "http://172.27.3.1:3000"; # gateway
          extraConfig = ''
            gzip on;
            gzip_types text/html text/css;
            etag on;
            add_header Alt-Svc 'h3=":443"; ma=86400';
          '';
        };
      };
      "hass.edwardh.dev" = {
        forceSSL = true;
        enableACME = true;
        quic = true;
        http3 = true;
        http3_hq = true;

        locations."/" = {
          recommendedProxySettings = true;
          proxyPass = "http://172.27.3.41:8123"; # rpi4-01
          proxyWebsockets = true;
          extraConfig = ''
            gzip on;
            gzip_types text/html text/css;
            etag on;
            add_header Alt-Svc 'h3=":443"; ma=86400';
          '';
        };
      };
    };
  };
}
